"""
@File   : model.py
@Time   : 2024/11/04 17:18:03
@Author : jiajun song

Model abstraction
"""

import abc
import dataclasses
from typing import Any, Dict, List, Optional, Union


class Model(abc.ABC):
    """Abstract language model class"""

    @abc.abstractproperty
    def model_meta(self) -> Dict[str, Any]:
        """Model meta information"""

    @abc.abstractmethod
    def generate_text(
        self,
        inputs: Union[str, List[str]],
        max_new_tokens: int,
        num_beams: int = 1,
        num_outputs: int = 1,
    ) -> Union[str, List[str]]:
        """Generates text for given inputs.

        Args:
          inputs: String or list of strings as inputs for model.
          max_new_tokens: Maximum number of new tokens to generate.
          num_beams: Number of beams to use for beam search.
          num_outputs: Number of outputs to generate.

        Returns:
          String or list of strings generated by model.
        """

    @abc.abstractmethod
    def cond_log_prob(
        self,
        inputs: Union[str, List[str]],
        targets: Union[List[str], List[List[str]]],
    ) -> Union[List[float], List[List[float]]]:
        """Computes conditional log probabilities of targets given inputs.

        Args:
          `inputs`: A single string input or a list of string inputs.

          `targets`: Possible string outputs for each input. If input is a
             string, this is a list `[t_1, t_2, ..., t_n]` of possible string
             outputs. If input is a list of strings, then this is a nested
             list `[[t_1, t_2, ..., t_n], ...]` with length equal to `len(inputs)`.


           Returns:
             If a single string input is provided, returns a list of
             log-probabilities `[lp_1, lp_2, ..., lp_n]` predicted by the model,
             where  `lp_i = log(prob(t_i | input)`  is the conditional log-prob
             to generate target `t_i` given input. If a list of string inputs
             was provided, returns a list of such elements of the form
             `[[lp_1, lp_2, ..., lp_n], ...]`, where each element contains the
             log-probabilities for the corresponding input and targets.
             In this case, the length of the returned list is `len(input)`.

             Note that no additional characters are appended to the inputs, or
             prepended to the targets. If there should be a space between the
             input and target, it should be explicitly included as the last character
             in the input.

             If conditional probabilities are not supported by the model, the
             model returns None.
        """
